dist: xenial
language: python

python:
  - 3.6
  - 3.7
  - 3.8

before_install:
  - pip freeze | xargs pip uninstall -y
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source "$HOME/.poetry/env"

install:
  - poetry install

script:
    - poetry run flake8 .
    - poetry run mypy dump_env
    - poetry run pytest
    - poetry run doc8 -q docs
    - poetry check
    - poetry run pip check
    - poetry run safety check --bare --full-report

after_success:
  - pip install coveralls
  - coveralls

notifications:
  email:
    on_success: never
    on_failure: change
